### ISSUE TITLE
old link in readme

### ISSUE THREAD

**Issue by virklba** [AzureADSamples/NativeClient-Headless-DotNet#4]
New link for Authentication Scenarios is https://azure.microsoft.com/en-us/documentation/articles/active-directory-authentication-scenarios/

**Comment by dstrockis** [comment]
Why thank you @virklba! 

https://github.com/AzureADSamples/NativeClient-Headless-DotNet/commit/cb367485fc038710d71185472299f0f88b53a37b

**Comment by virklba** [comment]
Most of the other AzureADSamples repos have this same link.

**Comment by dstrockis** [comment]
They do indeed... I made a note to update them all, thanks.

**Comment by dstrockis** [comment]
Done.... They were all fwLinks.
